#!/usr/bin/env bash
set -euo pipefail

echo "[pre-commit] Running cargo fmt --check..."
cargo fmt -- --check

echo "[pre-commit] Running cargo check..."
cargo check

echo "[pre-commit] Running cargo test..."
cargo test -q

echo "[pre-commit] Running functional test..."
./functional_tests/run_functional_tests.py

echo "[pre-commit] Running Check Advisory..."
cargo deny check advisories

echo "[pre-commit] All checks passed."
